services:
  db:
    image: mysql:8.0
    container_name: grid-talk-db
    restart: always
    environment:
      MYSQL_DATABASE: grid_talk
      MYSQL_ROOT_PASSWORD: user123
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql